#!/usr/bin/python3

import os
import sys
import inquirer
import re
import yaml

with open("index.yaml", "r") as f:
    index = yaml.load(f.read())

level_1 = []
for i in index:
    level_1.append(i)
    print(index[i])

questions_level_1 = [
    inquirer.List("search", message="What topic are you looking for", choices=level_1),
]

try:
    sys.argv[1]
    print(sys.argv[1])

    if sys.argv[1] == "ls":
        answers_1 = inquirer.prompt(questions_level_1)

        level_2 = []
        print(answers_1)

        for i in index[answers_1["search"]]:
            level_2.append(i)

        questions_level_2 = [
            inquirer.List(
                "search", message="What topic are you looking for", choices=level_2
            ),
        ]
        answers_2 = inquirer.prompt(questions_level_2)

        search_string = answers_2["search"].split(" ")[0]
        search_string = re.escape(search_string)

    else:
        search_string = text = input("Add your search string:")


except:
    search_string = text = input("Add your search string:")
    pass

# Future maybe remove false positives: grep -r "3\.1" *.md | grep -v "\.3\.1"
os.system(
    f"""
cd "$(dirname "{sys.argv[0]}")"
cd notes
grep -r --color=always  "{search_string}"
echo -n "Open notes in Virtual Studio Code(y/n)? "
old_stty_cfg=$(stty -g)
stty raw -echo ; answer=$(head -c 1) ; stty $old_stty_cfg # Careful playing with stty
if echo "$answer" | grep -iq "^y" ;then
    grep -r -l "{search_string}" | xargs code
else
    echo Ok!
fi
"""
)
