#!/usr/bin/python3

import sys
import re
import os
import yaml

with open("toread.md", "r") as f:
    text = f.read()

with open("config.yaml", "r") as c:
    shortcuts = yaml.load(c.read(), Loader=yaml.FullLoader)

if len(sys.argv) == 2:
    print(
        f'====== Pulling first QID in the "{shortcuts["lists"][sys.argv[1]]}" list ======'
    )
    regex = shortcuts["lists"][sys.argv[1]] + r"[\s\S]*?(Q[0-9]*)"
else:
    print("====== Pulling first QID in toread.md ======")
    regex = r"(Q[0-9]*)"
    code = ""

qid = re.findall(regex, text)[0]
print(qid)


if qid == "Q":
    print("No QID found.")

else:
    with open("toread.md", "w+") as f:
        f.write(text.replace(qid + "\n", ""))
    os.system(f"bash /home/lubianat/Documents/random/wikidata_bib/wread {qid}")

